### ISSUE TITLE
Create simple webpage

### ISSUE THREAD

**Issue by rwngwn** [prgcont/issues#2]
We should provide simple landing page with next meetup info etc.

Something like http://backendisti.cz/ should be awesome first step.

**Comment by abtris** [comment]
- use https://gohugo.io
- get theme from http://html5up.net/

**Comment by abtris** [comment]
Can we select some theme from https://themes.gohugo.io/ ?

**Comment by rwngwn** [comment]
for me i like:
- http://themes.gohugo.io/landing-page-hugo/
- http://themes.gohugo.io/creative/
- http://themes.gohugo.io/agency/

cc @veverjak

**Comment by jwerak** [comment]
I fancy http://themes.gohugo.io/creative/ one. I would only choose different theme color than orange. 
I suppose it will be possible... @abtris  ?

**Comment by abtris** [comment]
ok, I look into.

**Comment by abtris** [comment]
Can you add me write to containers-prague.github.io repo? I prepare PR with some basic version.

**Comment by rwngwn** [comment]
Done.

**Comment by abtris** [comment]
http://prgcont.cz/ done and we can move into #3
