### ISSUE TITLE
talk proposal: dockerized selenium grid with scriptform

### ISSUE THREAD

**Issue by jhrcz** [prgcont/issues#5]
* dockerized selenium grid (hub/nodes)
  * scriptform as "api" (https://github.com/fboender/scriptform)
  * jenkins cmdline api wrapper for executing env for tests inside nodes in grid

**Comment by czhujer** [comment]
it's great idea 👍

**Comment by jwerak** [comment]
@jhrcz up to the challenge ?

**Comment by rwngwn** [comment]
probably its outdated, if @jhrcz still want this talk, please fill [CFP form](https://docs.google.com/a/l-d-j.org/forms/d/e/1FAIpQLSd5wAgmpjevYnLymlVEKPf6kOx_07Fun_wA-Fpd1dg4yekdUQ/viewform)
